const EVENT_DATA = [
  {
    slug: "intercollege-football-tournament",
    title: "Intercollege Football Tournament",
    category: "Sports",
    date: "2026-05-10T09:00:00",
    venue: "North Campus Stadium",
    description: "A high-energy tournament featuring top college teams competing in knockout rounds with live commentary and food stalls.",
    tickets: ["General", "VIP", "Student"],
    registrations: 180,
    image: "Competitive football showdown",
    highlight: "Cheer for rising campus stars in a full-day football celebration."
  },
  {
    slug: "annual-marathon",
    title: "Annual Marathon",
    category: "Sports",
    date: "2026-05-18T06:00:00",
    venue: "Riverside Greenway",
    description: "Join runners, wellness groups, and volunteers for a scenic endurance marathon with hydration points and medals.",
    tickets: ["Runner Pass", "VIP", "Volunteer"],
    registrations: 260,
    image: "Sunrise marathon route",
    highlight: "Run a landmark route with a community-first atmosphere."
  },
  {
    slug: "cricket-league",
    title: "Cricket League",
    category: "Sports",
    date: "2026-05-26T15:30:00",
    venue: "Central Cricket Ground",
    description: "An exciting league fixture where city teams battle through a lively evening match with fan zones and refreshments.",
    tickets: ["General", "Premium", "Student"],
    registrations: 220,
    image: "Cricket league under lights",
    highlight: "Experience stadium energy and crowd-favorite matchups."
  },
  {
    slug: "rock-concert",
    title: "Rock Concert",
    category: "Music",
    date: "2026-06-03T19:30:00",
    venue: "Pulse Arena",
    description: "A live rock night with headline bands, dynamic lighting, and a crowd-ready stage setup for an unforgettable performance.",
    tickets: ["General", "VIP", "Backstage"],
    registrations: 340,
    image: "Rock stage lights",
    highlight: "Amplified performances, immersive lights, and all-night energy."
  },
  {
    slug: "classical-night",
    title: "Classical Night",
    category: "Music",
    date: "2026-06-11T18:00:00",
    venue: "Heritage Music Hall",
    description: "An elegant evening of classical vocals and instrumental performances presented in an intimate acoustic hall.",
    tickets: ["Standard", "Premium", "Student"],
    registrations: 150,
    image: "Classical performance hall",
    highlight: "A refined musical escape with timeless compositions."
  },
  {
    slug: "dj-party",
    title: "DJ Party",
    category: "Music",
    date: "2026-06-20T20:00:00",
    venue: "Skyline Terrace",
    description: "A high-tempo DJ experience with dance floors, LED visuals, themed beverages, and a rooftop party atmosphere.",
    tickets: ["General", "VIP", "Couple Pass"],
    registrations: 310,
    image: "Rooftop DJ party",
    highlight: "Dance-ready nightlife with panoramic city views."
  },
  {
    slug: "science-fair",
    title: "Science Fair",
    category: "Education",
    date: "2026-06-28T10:00:00",
    venue: "Innovation Pavilion",
    description: "Interactive exhibits, student prototypes, and live demonstrations that make science engaging for every visitor.",
    tickets: ["Entry", "Exhibitor", "School Group"],
    registrations: 280,
    image: "Science exhibits display",
    highlight: "Hands-on discovery with creative experiments and prototypes."
  },
  {
    slug: "coding-hackathon",
    title: "Coding Hackathon",
    category: "Education",
    date: "2026-07-06T09:30:00",
    venue: "Tech Innovation Lab",
    description: "A collaborative coding sprint where teams solve real-world problems, build prototypes, and pitch solutions to mentors.",
    tickets: ["Participant", "Mentor", "VIP"],
    registrations: 360,
    image: "Hackathon coding session",
    highlight: "Prototype fast, collaborate deeply, and pitch bold ideas."
  },
  {
    slug: "math-olympiad",
    title: "Math Olympiad",
    category: "Education",
    date: "2026-07-14T08:30:00",
    venue: "Academic Block A",
    description: "A competitive academic challenge designed to test analytical thinking, speed, and mathematical creativity.",
    tickets: ["Participant", "School Pass", "Faculty"],
    registrations: 190,
    image: "Math competition hall",
    highlight: "A focused competition for problem-solvers and young mathematicians."
  },
  {
    slug: "adventure-trek",
    title: "Adventure Trek",
    category: "Travel",
    date: "2026-07-22T05:30:00",
    venue: "Western Ridge Basecamp",
    description: "An action-filled guided trek with safety support, panoramic viewpoints, and a sunrise summit experience.",
    tickets: ["Explorer", "Pro Trek", "Group Pass"],
    registrations: 140,
    image: "Mountain trekking route",
    highlight: "Challenge yourself with scenic trails and expert guides."
  },
  {
    slug: "city-heritage-walk",
    title: "City Heritage Walk",
    category: "Travel",
    date: "2026-07-29T07:00:00",
    venue: "Old Town Square",
    description: "Discover iconic city landmarks, hidden architectural gems, and cultural stories through a guided urban walk.",
    tickets: ["Walker", "Family Pass", "Guide Plus"],
    registrations: 125,
    image: "Historic city walk",
    highlight: "Explore the city through stories, culture, and architecture."
  },
  {
    slug: "beach-camping",
    title: "Beach Camping",
    category: "Travel",
    date: "2026-08-08T16:00:00",
    venue: "Coral Bay Shoreline",
    description: "Enjoy sunset activities, bonfires, overnight tents, and group games in a relaxed beachside camping experience.",
    tickets: ["Camper", "VIP Tent", "Group Pass"],
    registrations: 210,
    image: "Beach campsite at dusk",
    highlight: "Sunset views, bonfires, and a memorable overnight escape."
  },
  {
    slug: "entrepreneurship-seminar",
    title: "Entrepreneurship Seminar",
    category: "Seminar",
    date: "2026-08-15T11:00:00",
    venue: "Business Convention Center",
    description: "Meet founders, learn startup strategy, and gain practical insights into funding, growth, and innovation.",
    tickets: ["Delegate", "VIP", "Student"],
    registrations: 240,
    image: "Seminar keynote session",
    highlight: "Practical startup ideas from founders and mentors."
  },
  {
    slug: "data-science-workshop",
    title: "Data Science Workshop",
    category: "Seminar",
    date: "2026-08-23T10:30:00",
    venue: "Digital Learning Hub",
    description: "A workshop covering data analysis, machine learning basics, and applied case studies with instructor-led sessions.",
    tickets: ["Workshop Pass", "VIP", "Student"],
    registrations: 275,
    image: "Data science training room",
    highlight: "Learn practical analytics skills from guided sessions."
  },
  {
    slug: "leadership-talk",
    title: "Leadership Talk",
    category: "Seminar",
    date: "2026-08-30T17:30:00",
    venue: "Summit Auditorium",
    description: "A thought-provoking talk on vision, team building, and communication by accomplished leaders and coaches.",
    tickets: ["General", "Front Row", "Student"],
    registrations: 205,
    image: "Leadership keynote audience",
    highlight: "Inspiring strategies for leading with clarity and confidence."
  }
];
